### ISSUE TITLE
This plugin is for an older version of ManicTime

### ISSUE THREAD

**Issue by ChrisSoper1** [manictime/manictime-client-plugin-example#1]
Building and installing the sample TagSource plugin results in this error being displayed in the plugin manager

**Comment by Anil86** [comment]
@manictime @Andrejf @vanjar I want to retrieve data from ManicTime using Tag Source plugin & then calculate some data patterns using Machine Learning. 
Currently this sample doesn't work. Please provide working sample for latest ManicTime. 

Thanks.

ManicTime version 3.7.2.0

**Comment by Anil86** [comment]
@jurijr  I tried Tag Plugin Template sample. It shows options for importing but as shown in demo on GitHub, export option is missing.

 What can I do (or is something missing)?

**Comment by jurijr** [comment]
@Anil86 

Following line at ClientPlugin.cs, adds the export option ("Send tags") to TagPluginTemplate plugin action menu.

`//add Send tags command button`
`pluginCommandRegistry.RegisterCommand<ExportTagsCommand>(pluginContext.Spec);`

If you are using "Keep user interface running when main window closes" setting, you have to restart entire tracker, not just reopen client to re-load plugin.

Another thing to consider before using Tag plugin in ManicTime, which might be your case, is that you have to create a tag source instance of it. 
This require you to set up plugin settings, which can be accomplished under 

> Tags > Tag Editor > Tag sources > Add > Tag plugin template

, or 

> Plugin manager > Tag plugin template > Settings

**Comment by Anil86** [comment]
@jurijr Thanks, it's working. after turning off  "Keep user interface running when main window closes".

Is it possible to export all tags (with start & end time) of ManicTime using plugin of type: "Tag Source Plugin"? 
The demo shows "Tag Plugin" exports only tags created via "Tag Plugin".

**Comment by jurijr** [comment]
@Anil86 

Please refer to code comments.
The sample plugin is only guideline on how to handle specific classes and recommended workflow from our libraries.

> Tag activities for the selected date range. All activities are returned. 
            We usually append a hidden tag (the ones preceded with a colon (:)) so we know which plugin was responsible for them.
            Below we filter the list to get only tags from this plugin. You can easily just skip that and process all of them.

> In this sample we only get the tags from this plugin, then save them to a local file.

Following line filters activities related only to current plugin.

`var pluginTags = allTagActivities
                .Where(ta => ta.Groups.Select(g => g.DisplayKey.ToLower()).Contains(ClientPlugin.HiddenTagLabel.ToLower()));`

Means if you 'd like to "export" all activities you don't filter them here, as allTagActivities already contains the array your looking for.


If your not familiar with C#, and your goal is only to retrieve the list once, further process it in your desired programming language, you can still do that by exporting tags into .csv file.

> Options > Import and export > Export

**Comment by Anil86** [comment]
@jurijr Thanks for your help. It's working now.
I was not able to understand relationship between various classes.
