### ISSUE TITLE
The requested service IEventHub has not been registered

### ISSUE THREAD

**Issue by aaron-hardin** [manictime/manictime-client-plugin-example#10]
I'm generally having a lot of issues running the Tag Plugin in ManicTime v4.7.5.1

This stack trace is the first issue that I ran into, and I'm wondering if this repo has not been updated to account for some changes in the plugin api.

> Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'Finkit.ManicTime.Common.IEventHub' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
>    at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable\`1 parameters)
>    at Finkit.ManicTime.Shared.ObjectBuilding.ComponentContextExtensions.ResolveUnregistered(IComponentContext container, Type serviceType, IDictionary\`2 parameters)
>    at Finkit.ManicTime.Shared.ObjectBuilding.AutofacObjectBuilder.Build(Type objectType, ConstructorParameter[] parameters)
>    at Finkit.ManicTime.Shared.Plugins.ServiceProviders.PluginCommands.PluginCommandRegistry.<>c__DisplayClass7_0.<ResolveCommands>b__0(Type t)
>    at System.Linq.Utilities.<>c__DisplayClass2_0\`3.<CombineSelectors>b__0(TSource x)
>    at System.Linq.Enumerable.SelectIPartitionIterator\`2.PreallocatingToArray(Int32 count)
>    at System.Linq.Enumerable.SelectIPartitionIterator\`2.ToArray()
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable\`1 source)
>    at Finkit.ManicTime.Shared.Plugins.ServiceProviders.PluginCommands.PluginCommandRegistry.ResolveCommands(IEnumerable\`1 commandTypes, PluginSpec spec)
>    at Finkit.ManicTime.Shared.Plugins.ServiceProviders.PluginCommands.PluginCommandRegistry.<ResolveCommands>b__6_0(KeyValuePair\`2 kv)
>    at System.Linq.Enumerable.SelectEnumerableIterator\`2.ToArray()
>    at System.Linq.Buffer\`1..ctor(IEnumerable\`1 source)
>    at System.Linq.OrderedEnumerable\`1.ToArray()
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable\`1 source)
>    at Finkit.ManicTime.Shared.Plugins.ServiceProviders.PluginCommands.PluginCommandRegistry.ResolveCommands()
>    at Finkit.ManicTime.Client.Views.MainView.PluginMenu.PluginMenuViewModel.EnumerateItems()+MoveNext()
>    at System.Collections.Generic.LargeArrayBuilder\`1.AddRange(IEnumerable\`1 items)
>    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable\`1 source)
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable\`1 source)
>    at Finkit.ManicTime.Client.Views.MainView.PluginMenu.PluginMenuViewModel.EnsureLoaded()
>    at Finkit.ManicTime.Client.Views.MainView.PluginMenu.PluginMenuViewModel.GetEnumerator()
>    at Finkit.ManicTime.Client.Views.MainView.PluginMenu.PluginMenuViewModel.System.Collections.IEnumerable.GetEnumerator()
>    at MS.Internal.Data.EnumerableCollectionView.LoadSnapshotCore(IEnumerable source)
>    at MS.Internal.Data.EnumerableCollectionView..ctor(IEnumerable source)
>    at MS.Internal.Data.ViewManager.GetViewRecord(Object collection, CollectionViewSource cvs, Type collectionViewType, Boolean createView, Func\`2 GetSourceItem)
>    at MS.Internal.Data.DataBindEngine.GetViewRecord(Object collection, CollectionViewSource key, Type collectionViewType, Boolean createView, Func\`2 GetSourceItem)
>    at System.Windows.Data.CollectionViewSource.GetDefaultCollectionView(Object source, Boolean createView, Func\`2 GetSourceItem)
>    at System.Windows.Data.CollectionViewSource.GetDefaultCollectionView(Object source, DependencyObject d, Func\`2 GetSourceItem)
>    at System.Windows.Controls.ItemCollection.SetItemsSource(IEnumerable value, Func\`2 GetSourceItem)
>    at System.Windows.Controls.ItemsControl.OnItemsSourceChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
>    at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
>    at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
>    at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
>    at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp)
>    at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
>    at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
>    at System.Windows.Data.BindingExpression.Activate(Object item)
>    at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
>    at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
>    at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
>    at MS.Internal.Data.DataBindEngine.Run(Object arg)
>    at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
>    at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
>    at System.Windows.ContextLayoutManager.UpdateLayout()
>    at System.Windows.UIElement.UpdateLayout()
>    at System.Windows.Interop.HwndSource.SetLayoutSize()
>    at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
>    at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
>    at System.Windows.Window.SetRootVisual()
>    at System.Windows.Window.SetRootVisualAndUpdateSTC()
>    at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
>    at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
>    at System.Windows.Window.CreateSourceWindowDuringShow()
>    at System.Windows.Window.SafeCreateWindowDuringShow()
>    at System.Windows.Window.ShowHelper(Object booleanBox)
>    at System.Windows.Window.Show()
>    at Finkit.ManicTime.Client.Main.Logic.MainWindowController.ActivateMainWindow(Boolean activateAsTopmost)
>    at Finkit.ManicTime.Client.Logic.ClientApplication.ManicTimeClient.ApplicationController.ActivateMainWindow()
>    at Finkit.ManicTime.Client.Logic.ClientApplication.ManicTimeClient.ApplicationController.ShowMainWindow()
>    at Finkit.ManicTime.Client.Logic.ClientApplication.ManicTimeClient.ClientApplicationInstance.Run()
>    at Finkit.ManicTime.Client.WpfApp.App.StartApplication(StartupEventArgs e)
>    at Finkit.ManicTime.Client.WpfApp.App.Application_Startup(Object sender, StartupEventArgs e)
>    at System.Windows.Application.OnStartup(StartupEventArgs e)
>    at System.Windows.Application.<.ctor>b__1_0(Object unused)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 
> System.Object:
> 
> 
> ***ManicTime Version 4.7.5.1

**Comment by aaron-hardin** [comment]
this appears to be a versioning issue, if I use Finkit.ManicTime.Common.dll from "C:\Program Files (x86)\ManicTime\Libs\Finkit.ManicTime.Common\4.7.5.1\" then it starts up correctly.

Is there a way to build plugins that aren't tied to a specific version of ManicTime?

**Comment by jurijr** [comment]
> this appears to be a versioning issue, if I use Finkit.ManicTime.Common.dll from "C:\Program Files (x86)\ManicTime\Libs\Finkit.ManicTime.Common\4.7.5.1" then it starts up correctly.
> 
> Is there a way to build plugins that aren't tied to a specific version of ManicTime?

If you delete ManicTime libraries from plugin lib folder, it should work regardless of version, we try to not break the api, unless we upgrade to next major version.
