### ISSUE TITLE
Tracker Plugin wont build

### ISSUE THREAD

**Issue by Matti-Elsing** [manictime/manictime-client-plugin-example#11]
Since the new version of ManicTime the Tracker Plugin will give the error CS0117.
And even when Building the Tag Plugin, the Window to send the Tags disappeared.

**Comment by Step92** [comment]
I am experiencing the same issue when trying to build the Tracker Plugin, just as the documentation recommends it for when you want to test the plugin. The exact error code is:

> ...\source\tracker-plugin\ManicTimePluginTester\App.xaml.cs(25,28): error CS0117: "ApplicationLog" does not contain a definition for "Filepath". [...\source\tracker-plugin\ManicTimePluginTester\ManicTimePluginTester.csproj] <

**Comment by jurijr** [comment]
Both issues had now been resolved, let us know if you find any other problems.
