### ISSUE TITLE
Access AutoTag activity from export plugin

### ISSUE THREAD

**Issue by core44** [manictime/manictime-client-plugin-example#17]
Is there a way to access AutoTag activity via a plugin?

I've written a plugin based on the SampleTagPlugin exporter which connects to the Harvest timetracking API and adds tag activity as Harvest Time Entries, which all works perfectly. However I'm only able to get tag activity for manually added tags, but my ManicTime workflow relies solely on AutoTags. I'd rather not have to constantly send autotags to tags in the GUI so my time gets picked up by my plugin. 

I've looked at editing `GetTagActivitiesAsync()` to try and make it get activity from the AutoTag timeline but with no success. What would be the correct way to achieve this? Thanks.

**Comment by jurijr** [comment]
Hi,

we are not officially supporting this API but at the moment you can inject instance of `SearchActivityFetcher` named e.g. _searchActivityFetcher.

Then consume it like this:

```
private AutoTagActivity[] GetAutoTagActivities(int dateFrom, int dateTo)
{
    var timeline = _viewTimelineCache.Timelines
        .FirstOrDefault(t => t.TimelineType.TypeName == TimelineTypeNames.AutoTags);
    if (timeline == null)
        return Array.Empty<AutoTagActivity>();

    return _searchActivityFetcher
        .GetActivities(timeline, dateFrom, dateTo, CancellationToken.None)
        .Cast<AutoTagActivity>()
        .ToArray();
}
```

**Comment by core44** [comment]
Thank you for your quick help, that worked perfectly... Lots of time saved!

When you say not supporting this API, does that mean that the ability to have AutoTags managed by a plugin is not possible? At the moment I've built a separate app that grabs the projects I'm assigned to from Harvest and generates a JSON file (based on the format that the autotags export function spits out, with my predefined rules for each incoming tag). I'm periodically running my app and then importing that JSON into the autotag editor manually to keep my tags up to date.... I really was hoping to be able to automate this process somehow?

**Comment by jurijr** [comment]
> Thank you for your quick help, that worked perfectly... Lots of time saved!
> 
> When you say not supporting this API, does that mean that the ability to have AutoTags managed by a plugin is not possible? At the moment I've built a separate app that grabs the projects I'm assigned to from Harvest and generates a JSON file (based on the format that the autotags export function spits out, with my predefined rules for each incoming tag). I'm periodically running my app and then importing that JSON into the autotag editor manually to keep my tags up to date.... I really was hoping to be able to automate this process somehow?

Not supporting just means we wont keep any part of it documented and there might be unannounced breaking changes at some point(s). Currently API might have the capability to overwrite autotag list. We plan to add more stable documented public API for plugin, but it may not contain such low-level functions as it would get too big for maintenance.

**Comment by core44** [comment]
Thanks for the info. I think a quick and fairly straightforward option would be to allow users to specify a JSON or CSV file that autotags were read from on the fly. Any changes to autotags in the GUI would be reflected in in the file and vice versa. This would allow people to easily manage which autotags ManicTime is using to tag activity, whether it be manually or by some other app / script that can generate the JSON / CSV and save it to file.

All of the projects I work on have a unique ID, so I simply a generate a tag for each project using a generic set of rules, with the project ID as the keyword for the autotag to pick up. Then I just ensure anything I work on has a project ID in the filename / file path / email subject etc. and my time gets recorded. Being able to do this means you can completely automate your time recording across multiple projects without ever tagging activity... or even adding new tags.

For me the autotags functionality of MT is by far the most useful feature, I would love to see some more options to manage them and their rules dynamically.
