### ISSUE TITLE
Timeline plugin - How to use instructions incorrect?

### ISSUE THREAD

**Issue by jon-freed** [manictime/manictime-client-plugin-example#3]
Are the Timeline plugin "[How to use](https://github.com/manictime/manictime-client-plugin-example#timeline-plugin)" instructions correct?  

I am asking because when I am on the step "3. Click on Add timeline button", then I do not see the "Timeline plugin example" that is displayed in the step's screenshot.

My "db folder" is at "C:\Users\jon\AppData\Local\Finkit\ManicTime".  Here are the 11 files for the plugin that I have within that folder .  As far as I can tell, their paths match the path that is in the instructions.

\Plugins\Packages\TimelinePlugins.TrayTagStopwatch\PluginIcon.png
\Plugins\Packages\TimelinePlugins.TrayTagStopwatch\PluginSpec.json
\Plugins\Packages\TimelinePlugins.TrayTagStopwatch\Lib\Finkit.ManicTime.Client.dll
\Plugins\Packages\TimelinePlugins.TrayTagStopwatch\Lib\Finkit.ManicTime.Common.dll
\Plugins\Packages\TimelinePlugins.TrayTagStopwatch\Lib\Finkit.ManicTime.Shared.dll
\Plugins\Packages\TimelinePlugins.TrayTagStopwatch\Lib\PluginIcon.png
\Plugins\Packages\TimelinePlugins.TrayTagStopwatch\Lib\PluginSpec.json
\Plugins\Packages\TimelinePlugins.TrayTagStopwatch\Lib\TagPlugins.Core.dll
\Plugins\Packages\TimelinePlugins.TrayTagStopwatch\Lib\TimelinePlugins.TrayTagStopwatch.dll
\Plugins\Packages\TimelinePlugins.TrayTagStopwatch\Lib\TimelinePlugins.TrayTagStopwatch.dll.config
\Plugins\Packages\TimelinePlugins.TrayTagStopwatch\Lib\TimelinePlugins.TrayTagStopwatch.pdb

I am also attaching the files  to this issue.
[Packages.zip](https://github.com/manictime/manictime-client-plugin-example/files/1682378/Packages.zip)

I tried exiting ManicTime and restarting ManicTime before looking.  I tried restarting my entire computer before looking.  Neither made any difference.

So... when I go to my "Add Timeline" dialog window, why do I not see the "Timeline plugin example" item?

Incidentally, I did open the "Plugin manager", and I do not see the plugin there.  It is not in the "Installed plugins" tab, and it is not in the "More plugins" tab.

**Comment by jurijr** [comment]
@jon-freed 
We are sorry for the lack of plugin documentation and troubleshooting instructions. 
If there has been any problems loading the plugin you can look for clues in two places
- Plugin manager, as you already suggested
- Logs folder, for plugin type 'Timeline' files namely starting with 'ManicTimeClient'



Plugin "TrayTagStopwatch" has two issues inside plugin specification (PluginSpec.json) file

> Directory name must match plugin ID. (Plugin ID: 'TimelinePlugins.TrayTagStopwatch'; Directory name: 'ManicTime.TimelinePlugins.TrayTagStopwatch'.
Either change **Id** field to 'ManicTime.TimelinePlugins.TrayTagStopwatch' or change Build Output path folder name to match the Id


> Json content is formatted incorrectly. 

You will need to remove the last enclosing brace.



Furthermore, if you are building a plugin for version 4.0 and above, you will have to pull the latest version of this repository to see up-to-date examples.
