### ISSUE TITLE
Timeline example doesn't show up in "Add timeline" window

### ISSUE THREAD

**Issue by r3h0** [manictime/manictime-client-plugin-example#4]
I'm having trouble getting the timeline example to show up in ManicTime. Here's what I did:

1. Clone repo (located in `$REPO`)
1. Open timeline example (`$REPO\source\timeline-plugin\TimelinePlugin.sln`)
1. Build Release
1. Copy `$REPO\installable-plugin\Plugins\Packages\` to `C:\Users\me\AppData\Local\Finkit\ManicTime\Plugins`. _(Note that there was no "Packages" directory before I did this; the `Plugins` folder only contained `Cache`, `Cache.UI`, and `Storage` directories.)_
1. Note the location of the `PluginSpec.json` file: `C:\Users\me\AppData\Local\Finkit\ManicTime\Plugins\Packages\ManicTime.TagSource.SampleTagPlugin\PluginSpec.json`. There is a `Lib` folder there as well, which has some binaries in it.
1. Re-open ManicTime
1. Click the gear above the timeline
1. Click "Add timeline"
1. EXPECTED: Select custom plugin. ACTUAL: The custom plugin was not there.

Did I miss a step? Perhaps the folder structure has changed since the README was written for the timeline example?

**Comment by jurijr** [comment]
`Release` builds of plugins were not copied into `root\installable-plugin` directory.
If your still experiencing any issues after this commit, let us know.
