### ISSUE TITLE
Import & Export

### ISSUE THREAD

**Issue by nickalbrecht** [manictime/manictime-client-plugin-example#6]
Just going through trying to create a plugin for listing all open tickets assigned to me from a ticket management system, and present them in ManicTime as tags. This is pretty easy, no problem there. Though I did notice, that if I selectively pull one tag from the list, and not the entire `TagSourceItem` entry, I don't get any of the `HiddenTagLabel` the example has, so that's not going to work for exporting my items afterward. Fortunately it's not a big deal to simply regex the tags, and look for a anything matching the format the external ticketing systems uses for ticket numbers.

However now I'm trying to export the activities out to the time management system and I'm running into issues. I'd like to update the information in ManicTime so that I add another tag to any activities that have been newly exported. But all of the methods for updating groups expect a full `Group` object instance, or `Dictionary<string, Group>`, which I'm not sure where that comes into play here?

I see methods for updating, setting, adding, but none of their signatures seem to be really intuitive on how to use them when I'm running the export. Given the example, is it possible to modify the `TagActivity`s returned by (or inside of) the example `TagsExporter.ExportTags()` method?

**Comment by jurijr** [comment]
If I understand you correctly, you are trying to remember which tag activities you had already exported?

One of ways of doing this, is by keeping a list of exported tag activity ids in SampleTagSettings.
Note that you may want to handle the cases where you update or delete tag activity after exporting it or even modifying exported entries on management system manually.

```
var sampleSourceInstance = TagPluginsHelper.GetTagSourceInstances(_tagSourceService.GetTagSourceInstances(), ClientPlugin.Id).Single();
var sampleSettings = (SampleTagSettings)sampleSourceInstance.Settings;
sampleSettings.ExportedActivityIds = ...
_tagSourceService.SaveTagSourceInstance(sampleSourceInstance);
```

If this is not your intended usage, please let us know.

**Comment by nickalbrecht** [comment]
Hmm, that might work. Though I was originally hoping for having the visual feedback of the extra tag on each activity that has been migrated. Sort of a visual way to confirm which ones have been processed already. Though I guess if I'm just looking for a way to confirm that it was exported, I could just create a plugin to act as a new timeline, and retrieve the time recorded in the management site (regardless if it came from manic time originally or not) and show it that way.

Since you mentioned settings, whats the storage mechanism for them? Is there a practical size limit on it and I was curious how secure information in there is, like if I'm storing login/password information for an external service.

I also noticed the example is doing a fixed "all activities for current date". Typically I'm doing catch-up on tagging activities and recording them in my time tracker days later. Is there a way to retrieve from the application which activities are currently highlighted/selected, or possibly even what date being looked at through the UI?

Don't mean to bombard you with questions, but there isn't much documentation that I've found on interacting with the classes in ManicTime.

**Comment by jurijr** [comment]
Tag source instance settings are basically just serialized as json, so not recommended as storage for high amount of data.
The said json entry is stored in the ManicTime database, hence if you would password protect client the database is encrypted and everything in it should be protected.
In other way storing plain text password ofcourse by far isn't best practice, and should be enchanced with cryptography algorithms of your choosing before storing into tag source instance settings. 
Futhermore decryption secret keys can be hidden by obfuscating plugin assembly before release.

If you need to store large amounts of data, or simply store it in more effective way, each plugin has designated content folder in which you can create your own storage - perhaphs an sqlite database.

_ClientPlugin.cs_
`pluginContext.ContentDir`

For your last question, lack of documentation on ManicTime classes is deliberate. 
While the requested features might be doable, it is unsupported since plugins should be independent from the ManicTime client version as much as possible.

**Comment by nickalbrecht** [comment]
I've been making a lot of progress with the Import, but I have a few questions. Where do I write the code to encrypt a setting value before ManicTime tries to save it, but after the user has changed and clicked "Ok" on the settings screen? I've tried all sorts of things, but no matter what I try, every time I restart ManicTime and it tries to load my plugin, the password in the settings class is in plain text again. I'm assuming there must be someway to do this? Pretty much every ticketing system is going to require credentials or APIkey of some kind.

How do I write custom messages to the ManicTime log files?

Is any of the information provided by a plugin to ManicTime persisted between app restarts? Or is the plugin the authority on that data and should cache things internally to itself in between restarts? For example, if I provide a bunch of tags, or activities for a timeline; are they all re-requested from the plugin(s) the next time it's restarted?

**Comment by jurijr** [comment]
SampleTagSettings "password" field is supposed to be updated only (once) in its encrypted form - after it has been validated. Password should not need to be decrypted anywhere else than in actual authentication.
> SettingsViewModel.cs

`override Task OnOk()`


Log files can be written by
`ApplicationLog.WriteError`
`ApplicationLog.WriteInfo`


It is possible to persist list of tags provided by your plugin.
> SampleTagSourceInstance.cs 

TagSourceCache
`void Update(int sourceInstanceId, IEnumerable<TagSourceItem> tags, string timestamp, bool persist)`

`persist` parameter is what your looking for.
`timestamp` parameter can be used for cache invalidation/update (e.g. ETag - if timestamp has not changed, your not required to update again)

Stored value can then be retrieved

> SampleTagSource.cs

`override BasicTagSourceInstance CreateServerTagSourceInstance(ITagSourceSettings settings, string cacheTimestamp)`
